on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-all:
    runs-on: swsnr-rust
    steps:
      - run: rustup update
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: just test-all
