
# cargo-vet audits file

[[audits.bitflags]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "2.6.0 -> 2.7.0"

[[audits.cfg-expr]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.17.0 -> 0.17.2"

[[audits.log]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.4.22 -> 0.4.24"

[[audits.log]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.4.24 -> 0.4.25"

[[audits.pin-project-lite]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.2.15 -> 0.2.16"

[[audits.pkg-config]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.3.30 -> 0.3.31"
notes = "Just a small bug fix around cargo directives for build.rs, no critical changes."

[[audits.proc-macro2]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.89 -> 1.0.92"

[[audits.proc-macro2]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.92 -> 1.0.93"

[[audits.quote]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.37 -> 1.0.38"

[[audits.serde_json]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.134 -> 1.0.135"

[[audits.unicode-ident]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.13 -> 1.0.14"

[[trusted.async-trait]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2025-10-31"
notes = "swsnr trusts dtolnay"

[[trusted.autocfg]]
criteria = "safe-to-run"
user-id = 539 # Josh Stone (cuviper)
start = "2019-05-22"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.bstr]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-02"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.gio]]
criteria = "safe-to-run"
user-id = 3623
start = "2020-08-28"
end = "2025-10-31"
notes = "swsnr trusts sdroege"

[[trusted.gio-sys]]
criteria = "safe-to-run"
user-id = 3623
start = "2020-09-16"
end = "2025-10-31"
notes = "swsnr trusts sdroege"

[[trusted.glib]]
criteria = "safe-to-run"
user-id = 3623
start = "2020-02-14"
end = "2025-10-31"
notes = "swsnr trusts sdroege"

[[trusted.glib-macros]]
criteria = "safe-to-run"
user-id = 3623
start = "2021-07-08"
end = "2025-10-31"
notes = "swsnr trusts sdroege"

[[trusted.glib-sys]]
criteria = "safe-to-run"
user-id = 3623
start = "2020-09-16"
end = "2025-10-31"
notes = "swsnr trusts sdroege"

[[trusted.globset]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.gobject-sys]]
criteria = "safe-to-run"
user-id = 3623
start = "2022-01-15"
end = "2025-10-31"
notes = "swsnr trusts sdroege"

[[trusted.hashbrown]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.ignore]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.indexmap]]
criteria = "safe-to-run"
user-id = 539 # Josh Stone (cuviper)
start = "2020-01-15"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.memchr]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.regex-automata]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.regex-syntax]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.rustix]]
criteria = "safe-to-run"
user-id = 6825
start = "2021-10-29"
end = "2025-10-31"
notes = "swsnr trusts sunfishcode"

[[trusted.ryu]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2025-10-31"
notes = "swsnr trusts dtolnay"

[[trusted.serde]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-12-17"

[[trusted.serde_derive]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-12-17"

[[trusted.serde_repr]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-26"
end = "2025-10-31"
notes = "swsnr trusts dtolnay"

[[trusted.serde_spanned]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2025-10-31"
notes = "swsnr trusts epage"

[[trusted.slab]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-10-13"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.smallvec]]
criteria = "safe-to-run"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2025-11-03"
notes = "Trusted by mozilla"

[[trusted.syn]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-11-03"
notes = "swsnr trusts dtolnay"

[[trusted.target-lexicon]]
criteria = "safe-to-run"
user-id = 696 # Nick Fitzgerald (fitzgen)
start = "2024-07-30"
end = "2025-11-03"
notes = "Trusted by bytecode alliance"

[[trusted.thiserror]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-10-31"
notes = "swsnr trusts dtolnay"

[[trusted.thiserror-impl]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-10-31"
notes = "swsnr trusts dtolnay"

[[trusted.toml]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2025-10-31"
notes = "swsnr trusts epage"

[[trusted.toml_datetime]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2022-10-21"
end = "2025-10-31"
notes = "swsnr trusts epage"

[[trusted.toml_edit]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2025-10-31"
notes = "swsnr trusts epage"

[[trusted.walkdir]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2025-10-31"
notes = "swsnr trusts BurntSushi"

[[trusted.windows-sys]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-10-31"
notes = "swsnr trusts kennykerr"

[[trusted.windows-targets]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-11-03"
notes = "Trusted by mozilla and bytecode-alliance"

[[trusted.winnow]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2025-10-31"
notes = "swsnr trusts epage"
