name: Release

on:
  push:
    tags:
      - v*

jobs:
  vendor-dependencies:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo --version
      - run: tar --version
      - run: zstd --version
      - run: echo "${GITHUB_SHA}"
      # Generate a reproducible vendor bundle
      - run: env LC_ALL=C TZ=UTC0 echo "timestamp=$(git show --quiet --date='format-local:%Y-%m-%dT%H:%M:%SZ' --format="%cd" "${GITHUB_SHA}")" >> "$GITHUB_OUTPUT"
        id: timestamp
      - run: cargo vendor --locked
      - run: env LC_ALL=C tar --numeric-owner --owner 0 --group 0 --sort name --mode='go+u,go-w' --format=posix --pax-option=exthdr.name=%d/PaxHeaders/%f --pax-option=delete=atime,delete=ctime --mtime="${{ steps.timestamp.outputs.timestamp }}" -c -f vendor-${{ github.ref_name }}.tar.zst --zstd vendor
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: vendor-${{ github.ref_name }}.tar.zst
      - uses: actions/upload-artifact@v4
        with:
          name: vendor-${{ github.ref_name }}.tar.zst
          path: vendor-${{ github.ref_name }}.tar.zst

  git-archive:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: env LC_ALL=C TZ=UTC0 git archive --format tar --prefix 'gnome-search-providers-vscode-${{ github.ref_name }}/' --output 'gnome-search-providers-vscode-${{ github.ref_name }}.tar' "${{ github.sha }}"
      - run: zstd 'gnome-search-providers-vscode-${{ github.ref_name }}.tar'
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'gnome-search-providers-vscode-${{ github.ref_name }}.tar.zst'
      - uses: actions/upload-artifact@v4
        with:
          name: gnome-search-providers-vscode-${{ github.ref_name }}.tar.zst
          path: gnome-search-providers-vscode-${{ github.ref_name }}.tar.zst

  create-release:
    runs-on: ubuntu-latest
    needs: [git-archive, vendor-dependencies]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/**/*.tar.*
