name: Release

on:
  push:
    tags:
      - v*

jobs:
  vendor-dependencies:
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo vendor --locked
      - run: tar -c -f vendor.tar.zstd --zstd vendor
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: vendor.tar.zstd
      - uses: actions/upload-artifact@v4
        with:
          name: vendor.tar.zstd
          path: vendor.tar.zstd

  create-release:
    runs-on: ubuntu-latest
    needs: [vendor-dependencies]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ./binaries
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ./binaries/**/*.tar.*
