name: "Test & Lint"

on:
  push:
    branches: main
    # Don't run CI for tags; there's always a branch for the tag as well so
    # there's no point in testing it separately
    tags-ignore: '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo build --all-targets --locked
      - run: cargo clippy --all-targets --locked
      - run: cargo test --locked
      - run: cargo fmt -- --check
      - uses: EmbarkStudios/cargo-deny-action@v2

  # See https://mozilla.github.io/cargo-vet/configuring-ci.html
  cargo-vet:
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.10.0
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/cargo-vet
          key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
      - name: Add the tool cache directory to the search path
        run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
      - name: Ensure that the tool cache is populated with the cargo-vet binary
        run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
      - name: Invoke cargo-vet
        run: cargo vet --locked
